FROM node:20-alpine

# Install OpenSSL and other dependencies
RUN apk add --no-cache openssl postgresql-client

WORKDIR /app

# Kopieer package.json en package-lock.json
COPY package*.json ./

# Schone installatie van dependencies
RUN rm -rf node_modules \
    && npm install

# Kopieer de rest van de code
COPY . .

# Genereer Prisma client
RUN npx prisma generate

CMD ["npm", "run", "dev"]
