apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rate-limit-policy
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: seo-sea-backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rate-limit-config
  namespace: production
data:
  # Algemene rate limits
  general-rate-limit: |
    limit_req_zone $binary_remote_addr zone=general:10m rate=100r/s;
    limit_req zone=general burst=200 nodelay;

  # API specifieke rate limits
  api-rate-limit: |
    # SEO audit endpoints
    location /api/v1/seo/audit {
      limit_req_zone $binary_remote_addr zone=seo_audit:10m rate=10r/m;
      limit_req zone=seo_audit burst=5 nodelay;
    }

    # Content generatie endpoints
    location /api/v1/content/generate {
      limit_req_zone $binary_remote_addr zone=content_gen:10m rate=30r/m;
      limit_req zone=content_gen burst=10 nodelay;
    }

    # Analytics endpoints
    location /api/v1/analytics {
      limit_req_zone $binary_remote_addr zone=analytics:10m rate=60r/m;
      limit_req zone=analytics burst=20 nodelay;
    }

    # Keyword research endpoints
    location /api/v1/keywords {
      limit_req_zone $binary_remote_addr zone=keywords:10m rate=50r/m;
      limit_req zone=keywords burst=15 nodelay;
    }

  # IP whitelist voor bepaalde clients
  ip-whitelist: |
    geo $whitelist {
      default 0;
      # Interne IPs
      10.0.0.0/8 1;
      172.16.0.0/12 1;
      192.168.0.0/16 1;
    }
